package metallum.lib;

public class Strings {

    public static final String VANADIUM_INGOT_NAME = "ingotVanadium";
    public static final String VANADIUM_INGOT_DISPLAY_NAME = "Vanadium Ingot";
    public static final String VANADIUM_ORE_NAME = "oreVanadium";
    public static final String VANADIUM_ORE_DISPLAY_NAME = "Vanadium Ore";
    public static final String VANADIUM_HELMET_NAME = "vanadiumHelmet";
    public static final String VANADIUM_CHESTPLATE_NAME = "vanadiumChestplate";
    public static final String VANADIUM_LEGGINGS_NAME = "vanadiumLeggings";
    public static final String VANADIUM_BOOTS_NAME = "vanadiumBoots";
    public static final String VANADIUM_HELMET_DISPLAY_NAME = "Vanadium Helmet";
    public static final String VANADIUM_CHESTPLATE_DISPLAY_NAME = "Vanadium Chestplate";
    public static final String VANADIUM_LEGGINGS_DISPLAY_NAME = "Vanadium Leggings";
    public static final String VANADIUM_BOOTS_DISPLAY_NAME = "Vanadium Boots";
    public static final String VANADIUM_SWORD_NAME = "vanadiumSword";
    public static final String VANADIUM_PICK_NAME = "vanadiumPickaxe";
    public static final String VANADIUM_AXE_NAME = "vanadiumAxe";
    public static final String VANADIUM_SHOVEL_NAME = "vanadiumShovel";
    public static final String VANADIUM_HOE_NAME = "vanadiumHoe";
    public static final String VANADIUM_SWORD_DISPLAY_NAME = "Vanadium Sword";
    public static final String VANADIUM_PICK_DISPLAY_NAME = "Vanadium Pickaxe";
    public static final String VANADIUM_AXE_DISPLAY_NAME = "Vanadium Axe";
    public static final String VANADIUM_SHOVEL_DISPLAY_NAME = "Vanadium Shovel";
    public static final String VANADIUM_HOE_DISPLAY_NAME = "Vanadium Hoe";
    public static final String VANADIUM_ARMOR_FILE = "vanadium";
    public static final String ITEM_ID_CONFIG_CATEGORY = "Item ID Start";
    public static final String BLOCK_ID_CONFIG_CATEGORY = "Block ID Start";
    public static final String THORIUM_SWORD_NAME = "thoriumSword";
    public static final String THORIUM_SWORD_DISPLAY_NAME = "Thorium Sword";
    public static final String THORIUM_INGOT_NAME = "ingotThorium";
    public static final String THORIUM_INGOT_DISPLAY_NAME = "Thorium Ingot";
    public static final String THORIUM_ORE_NAME = "oreThorium";
    public static final String THORIUM_ORE_DISPLAY_NAME = "Thorium Ore";
    public static final String VANADIUM_BLOCK_NAME = "blockVanadium";
    public static final String THORIUM_BLOCK_NAME = "blockThorium";
    public static final String VANADIUM_BLOCK_DISPLAY_NAME = "Vanadium Block";
    public static final String THORIUM_BLOCK_DISPLAY_NAME = "Thorium Block";
    public static final String THORIUM_PICK_DISPLAY_NAME = "Thorium Pickaxe";
    public static final String THORIUM_AXE_DISPLAY_NAME = "Thorium Axe";
    public static final String THORIUM_SHOVEL_DISPLAY_NAME = "Thorium Shovel";
    public static final String THORIUM_HOE_DISPLAY_NAME = "Thorium Hoe";
    public static final String THORIUM_PICK_NAME = "thoriumPickaxe";
    public static final String THORIUM_AXE_NAME = "thoriumAxe";
    public static final String THORIUM_SHOVEL_NAME = "thoriumShovel";
    public static final String THORIUM_HOE_NAME = "thoriumHoe";
    public static final String THORIUM_ARMOR_FILE = "thorium";
    public static final String THORIUM_HELMET_NAME = "thoriumHelmet";
    public static final String THORIUM_CHESTPLATE_NAME = "thoriumChestplate";
    public static final String THORIUM_LEGGINGS_NAME = "thoriumLeggings";
    public static final String THORIUM_BOOTS_NAME = "thoriumBoots";
    public static final String THORIUM_HELMET_DISPLAY_NAME = "Thorium Helmet";
    public static final String THORIUM_CHESTPLATE_DISPLAY_NAME = "Thorium Chestplate";
    public static final String THORIUM_LEGGINGS_DISPLAY_NAME = "Thorium Leggings";
    public static final String THORIUM_BOOTS_DISPLAY_NAME = "Thorium Boots";
    public static final String TEXTURE_FOLDER = "metallum";
}
